[package]
name = "io_uring_monoio"
version = "0.1.0"
edition = "2021"

[dependencies]
monoio = { version = "0.2.3", features = ["macros", "utils", "iouring"] }
itertools = "0.13.0"
log = "0.4.22"
tracing-subscriber = "0.3.18"